
package br.com.nfse.api.stubs;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "NfseService", targetNamespace = "http://NFSe.wsservices.systempro.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
@XmlRootElement(name = "NfseService")
public interface NfseService {


    /**
     * 
     * @param nfseCabecMsg
     * @param nfseDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SubstituirNfse")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SubstituirNfse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.SubstituirNfse")
    @ResponseWrapper(localName = "SubstituirNfseResponse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.SubstituirNfseResponse")
    @Action(input = "http://NFSe.wsservices.systempro.com.br/NfseService/SubstituirNfseRequest", output = "http://NFSe.wsservices.systempro.com.br/NfseService/SubstituirNfseResponse")
    public String substituirNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseCabecMsg
     * @param nfseDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GerarNfse")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GerarNfse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.GerarNfse")
    @ResponseWrapper(localName = "GerarNfseResponse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.GerarNfseResponse")
    @Action(input = "http://NFSe.wsservices.systempro.com.br/NfseService/GerarNfseRequest", output = "http://NFSe.wsservices.systempro.com.br/NfseService/GerarNfseResponse")
    public String gerarNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseCabecMsg
     * @param nfseDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelarNfse")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelarNfse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.CancelarNfse")
    @ResponseWrapper(localName = "CancelarNfseResponse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.CancelarNfseResponse")
    @Action(input = "http://NFSe.wsservices.systempro.com.br/NfseService/CancelarNfseRequest", output = "http://NFSe.wsservices.systempro.com.br/NfseService/CancelarNfseResponse")
    public String cancelarNfse(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseCabecMsg
     * @param nfseDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultarNfseFaixa")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNfseFaixa", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.ConsultarNfseFaixa")
    @ResponseWrapper(localName = "ConsultarNfseFaixaResponse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.ConsultarNfseFaixaResponse")
    @Action(input = "http://NFSe.wsservices.systempro.com.br/NfseService/ConsultarNfseFaixaRequest", output = "http://NFSe.wsservices.systempro.com.br/NfseService/ConsultarNfseFaixaResponse")
    public String consultarNfseFaixa(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

    /**
     * 
     * @param nfseCabecMsg
     * @param nfseDadosMsg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "EnviarLoteRpsSincrono")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EnviarLoteRpsSincrono", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.EnviarLoteRpsSincrono")
    @ResponseWrapper(localName = "EnviarLoteRpsSincronoResponse", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", className = "br.com.nfse.api.stubs.EnviarLoteRpsSincronoResponse")
    @Action(input = "http://NFSe.wsservices.systempro.com.br/NfseService/EnviarLoteRpsSincronoRequest", output = "http://NFSe.wsservices.systempro.com.br/NfseService/EnviarLoteRpsSincronoResponse")
    public String enviarLoteRpsSincrono(
        @WebParam(name = "nfseCabecMsg", targetNamespace = "")
        String nfseCabecMsg,
        @WebParam(name = "nfseDadosMsg", targetNamespace = "")
        String nfseDadosMsg);

}
