
package br.com.nfse.api.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "NfseService", targetNamespace = "http://NFSe.wsservices.systempro.com.br/", wsdlLocation = "https://www.nfse.erechim.rs.gov.br:8181/NfseService/NfseService?wsdl")
public class NfseService_Service
    extends Service
{

    private static final URL NFSESERVICE_WSDL_LOCATION;
    private static final WebServiceException NFSESERVICE_EXCEPTION;
    private static final QName NFSESERVICE_QNAME = new QName("http://NFSe.wsservices.systempro.com.br/", "NfseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.nfse.erechim.rs.gov.br:8181/NfseService/NfseService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFSESERVICE_WSDL_LOCATION = url;
        NFSESERVICE_EXCEPTION = e;
    }

    public NfseService_Service() {
        super(__getWsdlLocation(), NFSESERVICE_QNAME);
    }

    public NfseService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFSESERVICE_QNAME, features);
    }

    public NfseService_Service(URL wsdlLocation) {
        super(wsdlLocation, NFSESERVICE_QNAME);
    }

    public NfseService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFSESERVICE_QNAME, features);
    }

    public NfseService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfseService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfseService
     */
    @WebEndpoint(name = "NfseServicePort")
    public NfseService getNfseServicePort() {
        return super.getPort(new QName("http://NFSe.wsservices.systempro.com.br/", "NfseServicePort"), NfseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfseService
     */
    @WebEndpoint(name = "NfseServicePort")
    public NfseService getNfseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://NFSe.wsservices.systempro.com.br/", "NfseServicePort"), NfseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFSESERVICE_EXCEPTION!= null) {
            throw NFSESERVICE_EXCEPTION;
        }
        return NFSESERVICE_WSDL_LOCATION;
    }

}
